In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from functools import reduce

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

In [2]:
# load in csv files
# enrollment data
enr_14_load = os.path.join('Enrollment Report_District_AUSTIN ISD_Campuses_Ethnicity_2013-2014.csv')
enr_15_load = os.path.join('Enrollment Report_District_AUSTIN ISD_Campuses_Ethnicity_2014-2015.csv')
enr_16_load = os.path.join('Enrollment Report_District_AUSTIN ISD_Campuses_Ethnicity_2015-2016.csv')
enr_17_load = os.path.join('Enrollment Report_District_AUSTIN ISD_Campuses_Ethnicity_2016-2017.csv')
enr_18_load = os.path.join('Enrollment Report_District_AUSTIN ISD_Campuses_Ethnicity_2017-2018 .csv')

# student data
std_15_load = os.path.join('StudPgmDistrictCampus15district227901.csv')
std_16_load = os.path.join('StudPgmDistrictCampus16district227901.csv')
std_17_load = os.path.join('StudPgmDistrictCampus17district227901.csv')
std_18_load = os.path.join('StudPgmDistrictCampus18district227901.csv')

In [3]:
# transfer data into dataframes
# enrollment data
enr_14 = pd.read_csv(enr_14_load, skiprows=2)
enr_15 = pd.read_csv(enr_15_load, skiprows=2)
enr_16 = pd.read_csv(enr_16_load, skiprows=2)
enr_17 = pd.read_csv(enr_17_load, skiprows=2)
enr_18 = pd.read_csv(enr_18_load, skiprows=2)

# student data
std_15 = pd.read_csv(std_15_load)
std_16 = pd.read_csv(std_16_load)
std_17 = pd.read_csv(std_17_load)
std_18 = pd.read_csv(std_18_load)

In [4]:
# create function to clean data

# put all dataframes into a list
data_frames = [std_15, std_16, std_17, std_18]

# create a function to clean all dataframes
def func(df):
    df2 = df.replace(-9999999, 2)
    df3 = df2[['CAMPUS NAME', 'TOTAL ENROLLMENT', 'TOTAL ECONOMICALLY DISADVANTAGED STUDENTS', 
              'TOTAL TITLE I STUDENTS', 'TOTAL AT RISK STUDENTS']]
#     df4 = df3.groupby('CAMPUS NAME').sum().reset_index()
    return df3

In [5]:
# call function
for i in range(0,len(data_frames)):
    data_frames[i] = func(data_frames[i])

In [6]:
# create function to clean data

# put all dataframes into a list
data_frames_X = [enr_14, enr_15, enr_16, enr_17]

# create a function to clean all dataframes
def func(df):
    df2 = df.replace(-9999999, 2)
    df3 = df2[['Year', 'Campus Name','Ethnicity Name', 'Enrollment by Ethnicity']]
#     df4 = df3.rename(columns={'Campus Name': 'CAMPUS NAME'})
    return df3

In [7]:
# call function
for i in range(0,len(data_frames_X)):
    data_frames_X[i] = func(data_frames_X[i])

In [8]:
# create array to hold data
d = {}

In [9]:
# put all data into one dataframe
d['2014-2015'] = data_frames[0].set_index('CAMPUS NAME')
d['2015-2016'] = data_frames[1].set_index('CAMPUS NAME')
d['2016-2017'] = data_frames[2].set_index('CAMPUS NAME')
d['2017-2018'] = data_frames[3].set_index('CAMPUS NAME')

master = pd.concat(d, axis=1)

In [10]:
master.head()

                                   2014-2015  \
                            TOTAL ENROLLMENT
AKINS H S                             2667.0
ALLISON EL                             487.0
ALTERNATIVE LEARNING CENTER            166.0
ANDERSON H S                          2224.0
ANDREWS EL                             657.0

                                                                       \
                            TOTAL ECONOMICALLY DISADVANTAGED STUDENTS
AKINS H S                                                      1847.0
ALLISON EL                                                      466.0
ALTERNATIVE LEARNING CENTER                                     134.0
ANDERSON H S                                                    594.0
ANDREWS EL                                                      640.0

                                                                           \
                            TOTAL TITLE I STUDENTS TOTAL AT RISK STUDENTS
AKINS H S                                     11.0                 1555.0
ALLISON EL                                   487.0                  350.0
ALTERNATIVE LEARNING CENTER                    9.0                  166.0
ANDERSON H S                                  11.0                  718.0
ANDREWS EL                                   657.0                  562.0

                                   2015-2016  \
                            TOTAL ENROLLMENT
AKINS H S                             2713.0
ALLISON EL                             545.0
ALTERNATIVE LEARNING CENTER            116.0
ANDERSON H S                          2270.0
ANDREWS EL                             594.0

                                                                       \
                            TOTAL ECONOMICALLY DISADVANTAGED STUDENTS
AKINS H S                                                      1798.0
ALLISON EL                                                      521.0
ALTERNATIVE LEARNING CENTER                                      94.0
ANDERSON H S                                                    518.0
ANDREWS EL                                                      570.0

                                                                           \
                            TOTAL TITLE I STUDENTS TOTAL AT RISK STUDENTS
AKINS H S                                     43.0                 1712.0
ALLISON EL                                   545.0                  412.0
ALTERNATIVE LEARNING CENTER                    2.0                  110.0
ANDERSON H S                                  16.0                  756.0
ANDREWS EL                                   594.0                  524.0

                                   2016-2017  \
                            TOTAL ENROLLMENT
AKINS H S                             2680.0
ALLISON EL                             460.0
ALTERNATIVE LEARNING CENTER            107.0
ANDERSON H S                          2217.0
ANDREWS EL                             572.0

                                                                       \
                            TOTAL ECONOMICALLY DISADVANTAGED STUDENTS
AKINS H S                                                      1673.0
ALLISON EL                                                      392.0
ALTERNATIVE LEARNING CENTER                                      74.0
ANDERSON H S                                                    501.0
ANDREWS EL                                                      537.0

                                                                           \
                            TOTAL TITLE I STUDENTS TOTAL AT RISK STUDENTS
AKINS H S                                     29.0                 1590.0
ALLISON EL                                   460.0                  332.0
ALTERNATIVE LEARNING CENTER                    2.0                  107.0
ANDERSON H S                                  11.0                  714.0
ANDREWS EL                                   572.0                  495.0

                                   2017-2018  \
                            TOTAL ENROLLMENT
AKINS H S                             2765.0
ALLISON EL                             479.0
ALTERNATIVE LEARNING CENTER            101.0
ANDERSON H S                          2222.0
ANDREWS EL                             504.0

                                                                       \
                            TOTAL ECONOMICALLY DISADVANTAGED STUDENTS
AKINS H S                                                      1691.0
ALLISON EL                                                      458.0
ALTERNATIVE LEARNING CENTER                                      82.0
ANDERSON H S                                                    493.0
ANDREWS EL                                                      470.0


                            TOTAL TITLE I STUDENTS TOTAL AT RISK STUDENTS
AKINS H S                                     44.0                 1621.0
ALLISON EL                                   479.0                  362.0
ALTERNATIVE LEARNING CENTER                    2.0                   95.0
ANDERSON H S                                  24.0                  732.0
ANDREWS EL                                   504.0                  439.0

In [12]:
# export data into a csv
path = '../../Final_Data/Austin_ISD_Clean/Data'
export_enr_11 = master.to_csv(os.path.join(path,'title_2014-.csv'))