In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as stats

In [3]:
school_type = pd.read_csv('data/SchoolType.csv')
school_type_df = pd.DataFrame(school_type)
school_type_df = school_type_df[school_type_df.columns[[9, 12]]]
school_type_df.head()

                             name    type
0    Blackshear Elementary School  public
1  Bryker Woods Elementary School  public
2         Casis Elementary School  public
3     Maplewood Elementary School  public
4       Mathews Elementary School  public

In [4]:
for index, row in school_type_df.iterrows():
    if "Elementary School" in school_type_df['name'][index]:
        school_type_df['name'][index] = school_type_df['name'][index].replace("Elementary School", "EL").upper()
    if "Middle School" in school_type_df['name'][index]:
        school_type_df['name'][index] = school_type_df['name'][index].replace("Middle School", "M S").upper()
    if "High School" in school_type_df['name'][index]:
        school_type_df['name'][index] = school_type_df['name'][index].replace("High School", "H S").upper()
        
school_type_df.head()

              name    type
0    BLACKSHEAR EL  public
1  BRYKER WOODS EL  public
2         CASIS EL  public
3     MAPLEWOOD EL  public
4       MATHEWS EL  public

In [9]:
title_one = pd.read_csv('data/title_one_2014-2018.csv')
title_one_df = pd.DataFrame(title_one)
title_one_df = title_one_df[['name', '2014-2015 TOTAL ENROLLMENT', '2014-2015 TOTAL TITLE I STUDENTS', '2015-2016 TOTAL ENROLLMENT', '2015-2016 TOTAL TITLE I STUDENTS', '2016-2017 TOTAL ENROLLMENT', '2016-2017 TOTAL TITLE I STUDENTS', '2017-2018 TOTAL ENROLLMENT', '2017-2018 TOTAL TITLE I STUDENTS']]
title_one_df

,name,2014-2015 TOTAL ENROLLMENT,2014-2015 TOTAL TITLE I STUDENTS,2015-2016 TOTAL ENROLLMENT,2015-2016 TOTAL TITLE I STUDENTS,2016-2017 TOTAL ENROLLMENT,2016-2017 TOTAL TITLE I STUDENTS,2017-2018 TOTAL ENROLLMENT,2017-2018 TOTAL TITLE I STUDENTS
0,AKINS H S,2667.0,11.0,2713.0,43.0,2680.0,29.0,2765.0,44.0
1,ALLISON EL,487.0,487.0,545.0,545.0,460.0,460.0,479.0,479.0
2,ALTERNATIVE LEARNING CENTER,166.0,9.0,116.0,2.0,107.0,2.0,101.0,2.0
3,ANDERSON H S,2224.0,11.0,2270.0,16.0,2217.0,11.0,2222.0,24.0
4,ANDREWS EL,657.0,657.0,594.0,594.0,572.0,572.0,504.0,504.0
5,AUSTIN H S,2085.0,11.0,2084.0,15.0,2145.0,10.0,2267.0,22.0
6,AUSTIN ISD CHILD DEVELOPMENT CENTE,NaN,NaN,62.0,0.0,78.0,0.0,170.0,2.0
7,AUSTIN ST HOSPITAL,20.0,0.0,19.0,0.0,23.0,0.0,16.0,0.0
8,BAILEY M S,917.0,11.0,872.0,2.0,899.0,8.0,1006.0,9.0
9,BALDWIN EL,742.0,0.0,787.0,2.0,794.0,0.0,810.0,2.0
10,BARANOFF EL,994.0,2.0,984.0,7.0,1020.0,2.0,1014.0,7.0
11,BARRINGTON EL,588.0,588.0,627.0,627.0,542.0,542.0,547.0,547.0
12,BARTON HILLS EL,419.0,2.0,407.0,2.0,427.0,0.0,455.0,2.0
13,BECKER EL,344.0,344.0,377.0,377.0,431.0,431.0,437.0,437.0
14,BEDICHEK M S,969.0,969.0,NaN,NaN,NaN,NaN,NaN,NaN
15,BEDICHEK MIDDLE,NaN,NaN,908.0,908.0,883.0,883.0,846.0,846.0
16,BLACKSHEAR EL,276.0,276.0,291.0,291.0,381.0,381.0,378.0,378.0
17,BLANTON EL,542.0,542.0,479.0,479.0,486.0,486.0,516.0,516.0
18,BLAZIER EL,967.0,967.0,842.0,842.0,813.0,813.0,860.0,860.0
19,BOONE EL,499.0,5.0,573.0,573.0,568.0,568.0,535.0,535.0
20,BOWIE H S,2871.0,2.0,2912.0,9.0,2894.0,11.0,2880.0,13.0
21,BRENTWOOD EL,581.0,2.0,617.0,2.0,644.0,2.0,675.0,2.0
22,BROOKE EL,347.0,347.0,254.0,254.0,272.0,272.0,246.0,246.0
23,BROWN EL,411.0,411.0,358.0,358.0,354.0,354.0,272.0,272.0
24,BRYKER WOODS EL,393.0,2.0,400.0,0.0,443.0,0.0,458.0,0.0
25,BURNET M S,1138.0,1138.0,1020.0,1020.0,1040.0,1040.0,967.0,967.0
26,CAMPBELL EL,253.0,253.0,220.0,220.0,194.0,194.0,187.0,187.0
27,CASEY EL,665.0,127.0,606.0,606.0,633.0,633.0,616.0,616.0
28,CASIS EL,806.0,0.0,793.0,2.0,817.0,0.0,765.0,2.0
29,CLAYTON EL,881.0,0.0,876.0,0.0,855.0,0.0,838.0,0.0
...,...,...,...,...,...,...,...,...,...
111,REAGAN H S,1229.0,1229.0,1302.0,1302.0,1255.0,1255.0,1252.0,1252.0
112,REILLY EL,277.0,277.0,274.0,274.0,268.0,268.0,238.0,238.0
113,RICHARDS SCH FOR YOUNG WOMEN LEADE,764.0,0.0,787.0,0.0,785.0,8.0,827.0,7.0
114,RIDGETOP EL,302.0,16.0,292.0,292.0,331.0,331.0,371.0,371.0
115,RODRIGUEZ EL,793.0,793.0,701.0,701.0,591.0,591.0,503.0,503.0
116,ROSEDALE,239.0,0.0,263.0,2.0,210.0,0.0,232.0,2.0
117,SADLER MEANS YWLA,341.0,166.0,369.0,369.0,399.0,399.0,388.0,388.0
118,SANCHEZ EL,436.0,436.0,407.0,407.0,353.0,353.0,258.0,258.0
119,SCHOOL FOR YOUNG MEN,391.0,166.0,NaN,NaN,NaN,NaN,NaN,NaN
120,SIMS EL,228.0,228.0,267.0,267.0,232.0,232.0,204.0,204.0
121,SMALL M S,1003.0,10.0,1006.0,5.0,1179.0,5.0,1231.0,14.0
122,ST ELMO EL,292.0,292.0,307.0,307.0,284.0,284.0,297.0,297.0
123,SUMMITT EL,774.0,2.0,815.0,2.0,833.0,5.0,844.0,7.0
124,SUNSET VALLEY EL,518.0,123.0,531.0,531.0,533.0,533.0,543.0,543.0
125,TRAVIS COUNTY DAY SCHOOL,15.0,0.0,6.0,2.0,11.0,0.0,8.0,0.0
126,TRAVIS COUNTY J J A E P,2.0,2.0,2.0,0.0,5.0,0.0,2.0,0.0
127,TRAVIS COUNTY JUVENILE DETENTION C,58.0,0.0,41.0,2.0,44.0,0.0,35.0,0.0
128,TRAVIS H S,1329.0,1329.0,1291.0,1290.0,1332.0,1332.0,1233.0,1233.0
129,TRAVIS HTS EL,498.0,498.0,522.0,522.0,548.0,548.0,518.0,518.0
130,UPHAUS EARLY CHILDHOOD CENTER,236.0,236.0,271.0,271.0,299.0,299.0,340.0,340.0
131,WALNUT CREEK EL,661.0,661.0,634.0,634.0,605.0,605.0,642.0,642.0
132,WEBB M S,691.0,691.0,699.0,699.0,677.0,677.0,664.0,664.0
133,WEBB PRI CENTER,249.0,249.0,217.0,217.0,262.0,262.0,246.0,246.0
134,WIDEN EL,589.0,589.0,566.0,566.0,558.0,558.0,522.0,522.0
135,WILLIAMS EL,513.0,513.0,458.0,458.0,458.0,458.0,466.0,466.0
136,WINN EL,338.0,338.0,304.0,304.0,241.0,241.0,259.0,259.0
137,WOOLDRIDGE EL,572.0,572.0,630.0,630.0,612.0,612.0,532.0,532.0
138,WOOTEN EL,725.0,725.0,613.0,613.0,568.0,568.0,503.0,503.0
139,ZAVALA EL,400.0,400.0,382.0,382.0,357.0,357.0,298.0,298.0
140,ZILKER EL,567.0,5.0,538.0,2.0,562.0,0.0,550.0,15.0

In [20]:
df = pd.merge(title_one_df, school_type_df, how='inner', on='name')

df['14-16 Total Enrollment Change'] = df['2015-2016 TOTAL ENROLLMENT'] - df['2014-2015 TOTAL ENROLLMENT']
df['15-17 Total Enrollment Change'] = df['2016-2017 TOTAL ENROLLMENT'] - df['2015-2016 TOTAL ENROLLMENT']
df['16-18 Total Enrollment Change'] = df['2017-2018 TOTAL ENROLLMENT'] - df['2016-2017 TOTAL ENROLLMENT']

df['14-15 Percent Title I'] = df['2014-2015 TOTAL TITLE I STUDENTS'] / df['2014-2015 TOTAL ENROLLMENT']
df['15-16 Percent Title I'] = df['2015-2016 TOTAL TITLE I STUDENTS'] / df['2015-2016 TOTAL ENROLLMENT']
df['16-17 Percent Title I'] = df['2016-2017 TOTAL TITLE I STUDENTS'] / df['2016-2017 TOTAL ENROLLMENT']
df['17-18 Percent Title I'] = df['2017-2018 TOTAL TITLE I STUDENTS'] / df['2017-2018 TOTAL ENROLLMENT']

df['14-16 Percent Title I Change'] = (df['15-16 Percent Title I'] - df['14-15 Percent Title I']) / df['14-15 Percent Title I'] * 100
df['15-17 Percent Title I Change'] = (df['16-17 Percent Title I'] - df['15-16 Percent Title I']) / df['15-16 Percent Title I'] * 100
df['16-18 Percent Title I Change'] = (df['17-18 Percent Title I'] - df['16-17 Percent Title I']) / df['16-17 Percent Title I'] * 100

df = df[['name', 'type', '14-16 Percent Title I Change', '14-16 Total Enrollment Change', '15-17 Percent Title I Change', '15-17 Total Enrollment Change', '16-18 Percent Title I Change', '16-18 Total Enrollment Change']]
df.replace(np.inf, 100, inplace=True)
df.replace(np.nan, 0, inplace=True)
df

,name,type,14-16 Percent Title I Change,14-16 Total Enrollment Change,15-17 Percent Title I Change,15-17 Total Enrollment Change,16-18 Percent Title I Change,16-18 Total Enrollment Change
0,AKINS H S,public,284.281071,46.0,-31.727699,-33.0,47.059924,85.0
1,ALLISON EL,public,0.000000,58.0,0.000000,-85.0,0.000000,19.0
2,ANDERSON H S,public,42.507008,46.0,-29.606450,-53.0,117.690860,5.0
3,ANDREWS EL,public,0.000000,-63.0,0.000000,-22.0,0.000000,-68.0
4,AUSTIN H S,public,36.429070,-1.0,-35.229215,61.0,108.160565,122.0
5,BAILEY M S,public,-80.879900,-45.0,287.986652,27.0,0.534294,107.0
6,BALDWIN EL,public,100.000000,45.0,-100.000000,7.0,100.000000,16.0
7,BARANOFF EL,public,253.556911,-10.0,-72.436975,36.0,252.071006,-6.0
8,BARRINGTON EL,public,0.000000,39.0,0.000000,-85.0,0.000000,5.0
9,BARTON HILLS EL,public,2.948403,-12.0,-100.000000,20.0,100.000000,28.0
10,BECKER EL,public,0.000000,33.0,0.000000,54.0,0.000000,6.0
11,BEDICHEK M S,public,0.000000,0.0,0.000000,0.0,0.000000,0.0
12,BLACKSHEAR EL,public,0.000000,15.0,0.000000,90.0,0.000000,-3.0
13,BLANTON EL,public,0.000000,-63.0,0.000000,7.0,0.000000,30.0
14,BLAZIER EL,public,0.000000,-125.0,0.000000,-29.0,0.000000,47.0
15,BOONE EL,public,9880.000000,74.0,0.000000,-5.0,0.000000,-33.0
16,BOWIE H S,public,343.664148,41.0,22.982416,-18.0,18.756313,-14.0
17,BRENTWOOD EL,public,-5.834684,36.0,-4.192547,27.0,-4.592593,31.0
18,BROOKE EL,public,0.000000,-93.0,0.000000,18.0,0.000000,-26.0
19,BROWN EL,public,0.000000,-53.0,0.000000,-4.0,0.000000,-82.0
20,BRYKER WOODS EL,public,-100.000000,7.0,0.000000,43.0,0.000000,15.0
21,BURNET M S,public,0.000000,-118.0,0.000000,20.0,0.000000,-73.0
22,CAMPBELL EL,public,0.000000,-33.0,0.000000,-26.0,0.000000,-7.0
23,CASEY EL,public,423.622047,-59.0,0.000000,27.0,0.000000,-17.0
24,CASIS EL,public,100.000000,-13.0,-100.000000,24.0,100.000000,-52.0
25,CLAYTON EL,public,0.000000,-5.0,0.000000,-21.0,0.000000,-17.0
26,COOK EL,public,0.000000,-90.0,0.000000,-32.0,0.000000,-68.0
27,COVINGTON M S,public,246.177847,7.0,0.000000,0.0,0.000000,0.0
28,COWAN EL,public,59.132007,-10.0,2194.073031,49.0,-92.927308,2.0
29,CROCKETT H S,public,104.924761,-36.0,-21.274970,53.0,50.013202,-49.0
...,...,...,...,...,...,...,...,...
78,PEASE EL,public,-100.000000,10.0,100.000000,-25.0,3.862661,-9.0
79,PECAN SPRINGS EL,public,0.000000,12.0,0.000000,6.0,0.000000,-16.0
80,PEREZ EL,public,0.000000,-52.0,0.000000,-29.0,0.000000,-73.0
81,PICKLE EL,public,0.000000,-51.0,0.000000,-57.0,0.000000,-94.0
82,PILLOW EL,public,318.705036,-64.0,0.000000,-9.0,0.000000,10.0
83,PLEASANT HILL EL,public,0.000000,39.0,0.000000,-64.0,0.000000,-37.0
84,PREMIER H S AT LANIER,charter,0.000000,0.0,0.000000,0.0,0.000000,0.0
85,PREMIER H S AT LANIER,charter,0.000000,0.0,0.000000,0.0,0.000000,0.0
86,PREMIER H S AT LANIER,charter,0.000000,0.0,0.000000,0.0,0.000000,0.0
87,PREMIER H S AT TRAVIS,charter,0.000000,0.0,0.000000,0.0,0.000000,0.0
88,PREMIER H S AT TRAVIS,charter,0.000000,0.0,0.000000,0.0,0.000000,0.0
89,PREMIER H S AT TRAVIS,charter,0.000000,0.0,0.000000,0.0,0.000000,0.0
90,REAGAN H S,public,0.000000,73.0,0.000000,-47.0,0.000000,-3.0
91,REILLY EL,public,0.000000,-3.0,0.000000,-6.0,0.000000,-30.0
92,RIDGETOP EL,public,1787.500000,-10.0,0.000000,39.0,0.000000,40.0
93,RODRIGUEZ EL,public,0.000000,-92.0,0.000000,-110.0,0.000000,-88.0
94,SANCHEZ EL,public,0.000000,-29.0,0.000000,-54.0,0.000000,-95.0
95,SIMS EL,public,0.000000,39.0,0.000000,-35.0,0.000000,-28.0
96,SMALL M S,public,-50.149105,3.0,-14.673452,173.0,168.172218,52.0
97,SUMMITT EL,public,-5.030675,41.0,144.597839,18.0,38.175355,11.0
98,TRAVIS H S,public,-0.077459,-38.0,0.077519,41.0,0.000000,-99.0
99,WALNUT CREEK EL,public,0.000000,-27.0,0.000000,-29.0,0.000000,37.0
100,WEBB M S,public,0.000000,8.0,0.000000,-22.0,0.000000,-13.0
101,WIDEN EL,public,0.000000,-23.0,0.000000,-8.0,0.000000,-36.0
102,WILLIAMS EL,public,0.000000,-55.0,0.000000,0.0,0.000000,8.0
103,WINN EL,public,0.000000,-34.0,0.000000,-63.0,0.000000,18.0
104,WOOLDRIDGE EL,public,0.000000,58.0,0.000000,-18.0,0.000000,-80.0
105,WOOTEN EL,public,0.000000,-112.0,0.000000,-45.0,0.000000,-65.0
106,ZAVALA EL,public,0.000000,-18.0,0.000000,-25.0,0.000000,-59.0
107,ZILKER EL,public,-57.843866,-29.0,-100.000000,24.0,100.000000,-12.0

In [21]:
stats.linregress(x=df['14-16 Total Enrollment Change'], y=df['14-16 Percent Title I Change'])

LinregressResult(slope=-0.8559449607655654, intercept=383.44351497749466, rvalue=-0.014640106766023188, pvalue=0.8804631468374476, stderr=5.678087962438074)

In [22]:
stats.linregress(x=df['15-17 Total Enrollment Change'], y=df['15-17 Percent Title I Change'])

LinregressResult(slope=0.6710295889902052, intercept=28.304865870518164, rvalue=0.1242204220421749, pvalue=0.20023499103991366, stderr=0.5206176406570172)

In [23]:
stats.linregress(x=df['16-18 Total Enrollment Change'], y=df['16-18 Percent Title I Change'])

LinregressResult(slope=0.15240481286791904, intercept=17.211638745778224, rvalue=0.1309862442968337, pvalue=0.17661891752051267, stderr=0.11203714834226502)